# This file was generated by GoReleaser. DO NOT EDIT.
cask "athq" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "5bbdcee0afb507c205b1442f62ebaeba5555f8bd96b0adfc43fb1c480253cf37"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb4c9de80ef2e63c458c0223d476328a540d0065f2e0317f5e479e99386ab966"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "db0890fc5d5181524a412fc0673baa78340db0aba38c0ee24c73439c0ff6d410"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ab6fee26b5935a1521e9f1d4676df5597961c61ad9a28382d85b6b3123cc3f5e"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "athq"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/athq"]
    end
  end

  # No zap stanza required
end
