# This file was generated by GoReleaser. DO NOT EDIT.
cask "athq" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "093566eb0a865e6ca0540f70704e9be8a3220a4ac049fa8cde83e1147f559e2f"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a738277139dab95b4841664819df78ea8b0b25a7a554740f93743f3a9bdc74ba"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e574b5668e408d483e40316fa4b2d5fc093831e4224308e3820e5684fdb2ea9"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c3f777e5d682bf38ccb0b9672ee4fd49cd8e74ae0efc20b3cadfef1b6d950d3f"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "athq"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/athq"]
    end
  end

  # No zap stanza required
end
