# This file was generated by GoReleaser. DO NOT EDIT.
cask "athq" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "371155de32d76b4f7458b2d671db0b65db968914844cf38c0c7a33114bfcb625"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "78d6fe232eb07313fbbc8410c10e18f0b0265ac9734c111002b848deeb83fdb3"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cd26a6546c4e425c00d408f3ce2d1f17f478fde758634f9d591592aa25b27abf"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e546d8f20e0bf96bc841c9053a39cf3f1922642a1ab2404306da7d084bfdf070"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "athq"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/athq"]
    end
  end

  # No zap stanza required
end
