# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "604931eb787f0096d88806f13272e0031c47a4cc9f65da5e8675d5777f2235a5"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "30b883c2884927672637c0c5b823a7d648fda13bd34571994c6d68b5ddff7dc6"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae910ad42193c77995d4e0e0c4e927db7bda246000104cb8a6a1422e3cd4f383"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2f09a3eb1339872b81916af9db3da135f93670db8c88445b8d43873c0805a44"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccr"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
  end

  # No zap stanza required

end
