# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "45d1cee96a70a2d182f7b6d22ef58ae104c2fe0aedd1e5c93352fe6608cff957"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7f98a04281ea82fa69fcf3e7fad6597936ab351a3fb08b05deb46fbdc00ba98"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bb365aaa6d14d74c97e29a7ea6f91abc0dbb4d361322e9719a1e3b35be7efdf8"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7b30f2c3f37eb0f7f6b8f647f507f09bbe54d526067e4c1b61165f64c6b6385"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccr"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
  end

  # No zap stanza required
end
