# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "fbc5c68e6bdefd73d6fea655d3314b4bfdf4f91fbd7bdcd46ba4a2992dc9c7aa"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b966fb9b43d2461e14a27b0b2abcc99a76a81ffef8111d70caa0c15eea623330"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1460a9ddcecfea547595189bc3d4aaa6e39fae93aa714950bcce9f0e4d3a541b"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5441fc3e49b4683dabd007477aed95cae34d4260fced173a222088daee21e2d9"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccr"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
  end

  # No zap stanza required

end
